### ISSUE TITLE
Browse WF code hints do not open before EWF is fully initialized

### ISSUE THREAD

**Issue by couzteau** [adobe/brackets-edge-web-fonts#104]
1. disconnect computer from internet
2. launch EC
3. go to CSS font family style and hit ctrl-space to pop the font hints

result font hint d not open.

**Comment by iwehrman** [comment]
I broke it, I'll fix it.

**Comment by iwehrman** [comment]
Turns out I did not break this. In fact, it never worked! The bad news is that it needs to be fixed in Brackets and is non-trivial to fix. The good news is that I submitted a pull request to fix it: adobe/brackets#3848. The other bad news is that it's kind of a crazy pull request and might not get merged. So I'm marking this fix-in-progress and tracking.

**Comment by iwehrman** [comment]
Still waiting for review on adobe/brackets#3848, which probably won't make it into Brackets Sprint 25.

**Comment by iwehrman** [comment]
This issue is closely related to #69.

**Comment by iwehrman** [comment]
Fixed by adobe/brackets#3848. Closing

**Comment by ryanstewart** [comment]
Awesome, thanks Ian!
