### ISSUE TITLE
PreferencesManager.convertPreferences() is deprecated

### ISSUE THREAD

**Issue by marcelgerber** [adobe/brackets-edge-web-fonts#175]
The new Preferences System in Brackets was introduced in Sprint 36 (released February 2014) and now that pretty much all remains of the old system are gone (that is, converted to the new format), the conversion function `PreferencesManager.convertPreferences()` is about to be removed in the near future, probably in Release 1.1. Your extension makes use of this method and thus, it'll probably not work any longer after that code is removed.
Simply remove the function call :)

For more information, take a look at https://github.com/adobe/brackets/issues/8751#issuecomment-60777334.

**Comment by le717** [comment]
Half of this (using the new API) was fixed with #169, but it looks like the change made in #174 to restore 1.0 and use the preferences was support were never pushed to the registry. @redmunds @jadbox Can we get the latest changes pushed to the registry so users can have their preferences converted, then this extension be updated to solely use the new system?

**Comment by redmunds** [comment]
@le717 PR #174 updated the version number in package.json to `0.1.6` and that's what's on the Registry, so it's up-to-date, correct?

**Comment by le717** [comment]
@redmunds Sorry about that. It does seem to be updated. I must have missed seeing that after you didn't have permission to update it.
