### ISSUE TITLE
[Win_only] 'Sample' after some fonts name cannot be displayed in Web font hints list.

### ISSUE THREAD

**Issue by Chen-Dandan** [adobe/brackets-edge-web-fonts#63]
1. Launch Brackets Sprint 19 5290.(after the latest file package "brackets-edge-web-fonts-master" has been put in Extensions folder)
2. Open a css file in left sidebar.
3. Type "font-family:" in the css file and press Ctrl-Space.
4. Observe the pop-up Web font hints list.

Result: The "Sample" string after fonts "andale mono" and "helvetica neue" cannot be displayed as other fonts, even wait for a long time. Please see the following screenshot.

Expected: All the "Sample" styles should be displayed well.

Notes: Repro only on Windows. Repro on EN.

Screenshot:
![Sample](https://f.cloud.github.com/assets/2245186/109870/e472aace-6a9f-11e2-8489-e02d9a6dfca8.png)

**Comment by joelrbrandt** [comment]
Thanks for taking a look at this.

This is expected behavior. If fonts are not available on a system or via Edge Web Fonts, we cannot display a sample. (If Andale Mono or Helvetica Neue were on your system or in EWF, they would be displayed.)

I'm going to close the bug for now. If you experience this problem with fonts that you _know_ are on your system/available in EWF, please re-open it.
