### ISSUE TITLE
Should add a License File

### ISSUE THREAD

**Issue by ryanstewart** [adobe/brackets-edge-web-fonts#85]
We should add a license to this repo. Potentially MIT so it's the same as Brackets - https://github.com/adobe/brackets/blob/master/LICENSE

**Comment by joelrbrandt** [comment]
And a README.md!

On Apr 16, 2013, at 1:46 PM, Ryan Stewart notifications@github.com wrote:

We should add a license to this repo. Potentially MIT so it's the same as
Brackets - https://github.com/adobe/brackets/blob/master/LICENSE

—
Reply to this email directly or view it on
GitHubhttps://github.com/adobe/brackets-edge-web-fonts/issues/85
.

**Comment by iwehrman** [comment]
@pthiess @julianasuh Can either of you comment about whether it's safe to call brackets-EWF MIT licensed?

**Comment by pthiess** [comment]
Hi @iwehrman:
We should just use MIT license for the code as well. However, we should put a prominent notice so users know that EWF have their own TOU, something along the lines of:

Notice to users: The code available on this site is governed by the MIT license. However, in order to use this API, you or your end users are required to have a valid license to Adobe Edge Web Fonts service. Use of Adobe Edge Web Fonts or any other software is governed under separate terms and licenses provided with such software. Nothing in this project grant rights to any other software or service.

**Comment by iwehrman** [comment]
A prominent notice where? In the license file?

**Comment by iwehrman** [comment]
Marking low priority because the lack of an explicit license file hasn't been a huge problem for the last year.

**Comment by julianasuh** [comment]
Please do not put in the license file.

I would check first with Ann.

Juliana

**Comment by ryanstewart** [comment]
Thanks @julianasuh. All, we'll add this to our list of things to go over with legal post MAX. I don't think it will be a huge deal but we should keep them in the loop. I agree with the low priority.

**Comment by julianasuh** [comment]
Notice to users can be added somewhere users can see. Confirmed with Ann.

**Comment by pthiess** [comment]
@julianasuh @ryanstewart  My comment was the actual advice from legal. IMHO we should add it - An MIT license like for Brackets and the note mentioned above. What's the problem?

**Comment by iwehrman** [comment]
I'll paste it wherever you like. I just don't know where to paste it. Are you envisioning that this is in the UI somewhere? Or just at the top of a LICENSE file?

**Comment by pthiess** [comment]
@ryanstewart - I will send this to Ann to regress.

**Comment by pthiess** [comment]
@iwehrman : Thanks just added.

**Comment by pthiess** [comment]
Verified by legal @ryanstewart - I go ahead and close
